
name: Build Enmity and Inject Rosiecord
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
    - cron: '0 12 * * *'

jobs:
  build:

    name: Build Enmity and Inject Rosiecord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Actions Status Discord Started
        uses: sarisia/actions-status-discord@v1.13.0
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          nodetail: true
          title: Building a new version of `Rosiecord`...
          description: | 
            I will send another message once its finished
          url: https://github.com/SerStars/rosiecord/releases
          content: Building!
          color: 0x000001

      - name: Ensure main utils are installed
        id: core
        run: brew install coreutils ldid

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel

      - name: Run Main Node Script to Patch Rosiecord
        id: build
        run: sh ./script.sh

      - name: Retrieve version
        id: version
        run: |
          cd ./ipas
          echo "__DISCORD_VERSION=$(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)" >> $GITHUB_OUTPUT

      - name: Run the PathFixer script
        run: |
          python pathfixer.py
        env:
          BASE_DIRECTORY: Dist

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.SERSTARS_BOT }}"
          prerelease: false
          automatic_release_tag: rosiecord_${{ steps.version.outputs.__DISCORD_VERSION }}
          title: Rosiecord ${{ steps.version.outputs.__DISCORD_VERSION }}
          files: Dist/*.ipa

      - name: Actions Status Discord Done
        uses: sarisia/actions-status-discord@v1.13.0
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          nodetail: true
          title: A new version of `Rosiecord` is ready!
          description: | 
            Version `${{ steps.version.outputs.__DISCORD_VERSION }}`
            Click [here](https://github.com/SerStars/rosiecord/releases/latest) to download
          url: https://github.com/SerStars/rosiecord/releases
          content: Ready!
          color: 0x000001
